world_size:	4
master_port:	12354
tensorboard:	True
num_epochs:	30
start_epoch:	1
start_batch:	0
exp_dir:	pruned_transducer_stateless_d2v_v2/d2v-T
bpe_model:	data/lang_bpe_500/bpe.model
base_lr:	0.05
lr_batches:	5000
lr_epochs:	3.5
context_size:	2
prune_range:	10
lm_scale:	0.25
am_scale:	0.0
simple_loss_scale:	0.5
ctc_loss_scale:	0.2
seed:	42
print_diagnostics:	False
inf_check:	False
save_every_n:	2000
keep_last_k:	30
average_period:	200
use_fp16:	True
num_encoder_layers:	2,4,3,2,4
feedforward_dims:	1024,1024,2048,2048,1024
nhead:	8,8,8,8,8
encoder_dims:	384,384,384,384,384
attention_dims:	192,192,192,192,192
encoder_unmasked_dims:	256,256,256,256,256
zipformer_downsampling_factors:	1,2,4,8,2
cnn_module_kernels:	31,31,31,31,31
decoder_dim:	768
joiner_dim:	768
wandb:	False
accum_grads:	4
multi_optim:	True
peak_enc_lr:	0.0003859
peak_dec_lr:	0.04175
encoder_type:	d2v
encoder_dim:	768
freeze_finetune_updates:	3000
additional_block:	True
decode_interval:	200
manifest_dir:	data/fbank
max_duration:	150
bucketing_sampler:	True
num_buckets:	30
concatenate_cuts:	False
duration_factor:	1.0
gap:	1.0
shuffle:	True
drop_last:	True
return_cuts:	True
num_workers:	2
enable_spec_aug:	False
spec_aug_time_warp_factor:	80
enable_musan:	True
input_strategy:	AudioSamples
